### ISSUE TITLE
Feature Request: Live preview. 

### ISSUE THREAD

**Issue by MarioRicalde** [ahkohd/FigmaDither#4]
It'd be nice to have a toggle that shows does changes live as you change the numbers and options. Experimenting and discovering right now is a bit painful as it closes every time you apply the effect.

**Comment by ahkohd** [comment]
Very well, how about a live preview support if you only make one selection. For multiple selection this can be memory intensive.

**Comment by ahkohd** [comment]
Thanks for reaching out.
