### ISSUE TITLE
Plugin not dithering

### ISSUE THREAD

**Issue by hlikosh** [ahkohd/FigmaDither#6]
While I was testing the plugin preview was working, but when I hit the Dither button - nothing changed, the image still had the same view. 

Maybe I'm not using it write.
Could you help me?

**Comment by ahkohd** [comment]
You should watch this. 
https://www.youtube.com/watch?v=hLhvk-kGlYQ

> Please note that **Dither** only works on nodes with that as image fills.So if you have wanted to Dither an SVG, you have to convert it to PNG or JPG.

**Comment by hlikosh** [comment]
The video is really great, but it does process nothing after I push the **Dither** button.
![ezgif-6-3c4a9ab04e70](https://user-images.githubusercontent.com/5880844/73447166-d7889880-4366-11ea-9164-d5de08503ee7.gif)

**I have tried to dither `.png` only.**

**Comment by ahkohd** [comment]
I downloaded a picture and tried dithering also, but apparently, It's strange that the plugin is broken. Thanks for reaching out, I will fix that now.

**Comment by ahkohd** [comment]
Hi, @hlikosh thanks for reporting this issue, #6 contains the fix to what is broken.
I have shipped the new update to  @Figma plugin store, **Dither version 4.**
You should update now, you rock! 🤗 

I recommend you check out other plugins I have made. https://www.figma.com/@victor_aremu
If you have a new plugin request, feel free to DM on twitter @ahkohd

**Comment by ahkohd** [comment]
Feedback will be helpful so as to decide if I should close this issue. Thanks!
